// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydkxyptycbtugzefwnmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlka3h5cHR5Y2J0dWd6ZWZ3bm1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyNTg5ODEsImV4cCI6MjA4ODgzNDk4MX0.hQ8atvCOHAmqYuwlINci8UcpZIHuGiKyNBy_8Caak8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
